// LOCALHOST
### Get all products
GET http://localhost:8000/products

### Get all customers
GET http://localhost:8000/customers

### Get products by id
GET http://localhost:8000/products/

### Get customers by id
GET http://localhost:8000/customers/

### Create product
POST http://localhost:8000/products HTTP/1.1
content-type: application/json

{
   "name": "4K Monitor",
   "price": 200,
   "quantity": 5,
   "brand": "Dell"
}

### Create customer
POST http://localhost:8000/customer HTTP/1.1
content-type: application/json

{
   "firstName": "Jonas",
   "lastName": "Pierre",
   "email": "jonaspierre@gmail.com",
   "phone": "8294825123"
}

### PUT product
PUT http://localhost:8000/products/6881670ab02df759c06982ff HTTP/1.1
content-type: application/json

{
   "firstName": "Jonas",
   "lastName": "Pierre",
   "email": "jonaspierre@gmail.com",
   "phone": "8294825123"
}

### PUT customer
PUT http://localhost:8000/customers/6881874db02df759c0698303 HTTP/1.1
content-type: application/json

{
   "firstName": "Leonel",
   "lastName": "Pierre",
   "email": "jonaspierre@gmail.com",
   "phone": "8294825123"
}

### Delete product
DELETE http://localhost:8000/products/6881670ab02df759c06982ff HTTP/1.1

### Delete customer
DELETE http://localhost:8000/customers/6881874db02df759c0698303 HTTP/1.1