// LOCALHOST
### Get all products
GET http://localhost:8000/products

### Get products by id
GET http://localhost:8000/products/

### Create product
POST http://localhost:8000/products HTTP/1.1
content-type: application/json

 {
    "name": "4K Monitor",
    "price": 200,
    "quantity": 5,
    "brand": "Dell"
 }

### PUT product
PUT http://localhost:8000/products/6881670ab02df759c06982ff HTTP/1.1
content-type: application/json

{
   "name": "5K Monitor",
    "price": 200,
    "quantity": 5,
    "brand": "Dell"
}

### Delete product
DELETE http://localhost:8000/products/6881670ab02df759c06982ff HTTP/1.1