// LOCALHOST
### Get all products
GET http://localhost:8000/products

### Get products by id
GET http://localhost:8000/products/

### Create product
POST http://localhost:8000/products HTTP/1.1
content-type: application/json

 {
   "firstName": "Joshua",
   "lastName": "Ocean",
   "email": "joshuaocean@gmail.com",
   "favoriteColor": "red",
   "birthday": "12-12-1986"
 }

### PUT product
PUT http://localhost:8000/products/ HTTP/1.1
content-type: application/json

{
   "firstName": "Joshua",
   "lastName": "Ocean",
   "email": "joshuaocean@gmail.com",
   "favoriteColor": "red",
   "birthday": "12-12-1986"
}

### Delete product
DELETE http://localhost:8000/products/ HTTP/1.1